In [1]:
# Initialisation
import pandas as pd
import numpy as np


In [2]:
# load 'iris' dataset
Iris = pd.read_csv('iris 3 Groups.csv')

In [3]:
Iris

sapallength  sepalwidth  petallength  petalwith           Class
0            5.1         3.5          1.4        0.2     Iris-setosa
1            4.9         3.0          1.4        0.2     Iris-setosa
2            4.7         3.2          1.3        0.2     Iris-setosa
3            4.6         3.1          1.5        0.2     Iris-setosa
4            5.0         3.6          1.4        0.2     Iris-setosa
..           ...         ...          ...        ...             ...
145          6.7         3.0          5.2        2.3  Iris-virginica
146          6.3         2.5          5.0        1.9  Iris-virginica
147          6.5         3.0          5.2        2.0  Iris-virginica
148          6.2         3.4          5.4        2.3  Iris-virginica
149          5.9         3.0          5.1        1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
Iris.info()

In [4]:
features = ['sapallength','sepalwidth','petallength','petalwith']

In [5]:
# We will need to build the clustering model using features only, ‘Class’ is used for evaluation purpose later
X = Iris [features]


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state = 42)

In [8]:
# import KMeans from sklearn
from sklearn.cluster import KMeans

In [9]:
# set number of cluster to be 3
kmeansmodel = KMeans(n_clusters=3)

In [10]:
# fit data
kmeansmodel.fit(X_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html
1. n_clusters:The number of clusters to form as well as the number of centroids to generate.
2. init: Method for initialization
3. n_init: Number of time the k-means algorithm will be run with different centroid seeds. The final results will be the best output of n_init consecutive runs in terms of inertia.
4. max_iter: Maximum number of iterations of the k-means algorithm for a single run.

In [11]:
# centroids
centroids = kmeansmodel.cluster_centers_
clustercentroids

array([[6.75769231, 3.08846154, 5.60384615, 2.02307692],
       [4.94444444, 3.33333333, 1.46296296, 0.24074074],
       [5.7972973 , 2.69459459, 4.34864865, 1.42432432]])

In [12]:
# number of iteration 
iteration = kmeansmodel.n_iter_
iteration

5

In [13]:
#Sum of squared distances of samples to their closest cluster center
SSD = kmeansmodel.inertia_
SSD

46.44977323477323

In [14]:
# Transform X to a cluster-distance space
distance = kmeansmodel.transform(X_train)
distance

array([[0.95160251, 4.0599452 , 0.83538   ],
       [4.579487  , 0.46687238, 2.99784071],
       [4.73832261, 0.36692845, 3.12777795],
       [4.51137123, 0.38563008, 2.95338016],
       [1.9961909 , 3.07315247, 0.27660152],
       [4.79689094, 0.17797057, 3.25539391],
       [1.94287882, 3.01554728, 0.41851768],
       [1.62082874, 6.25108934, 3.31251032],
       [5.06596574, 0.37688711, 3.44709361],
       [1.60293278, 3.30681219, 0.47136406],
       [1.35283507, 4.10742411, 0.89609982],
       [4.87988111, 1.03217112, 3.54233398],
       [1.1304225 , 3.84609078, 0.69225075],
       [1.15632426, 4.13693922, 0.88928776],
       [2.2321448 , 3.06784509, 0.76636754],
       [1.8284528 , 3.33586118, 0.52891554],
       [0.72547679, 4.61753977, 1.59119886],
       [2.30187408, 2.98914818, 0.6173354 ],
       [4.51401335, 0.7811479 , 3.11053489],
       [3.17262468, 2.24099172, 1.43913272],
       [0.6215437 , 4.4716605 , 1.22254509],
       [4.9122462 , 0.09910436, 3.34599725],
       [5.

In [15]:
# labels from training 
labels = kmeansmodel.predict(X_train)
labels

array([2, 1, 1, 1, 2, 1, 2, 0, 1, 2, 2, 1, 2, 2, 2, 2, 0, 2, 1, 2, 0, 1,
       1, 2, 0, 1, 0, 1, 1, 2, 2, 0, 2, 0, 0, 2, 1, 1, 2, 0, 1, 1, 1, 2,
       0, 1, 0, 0, 1, 2, 2, 2, 0, 0, 1, 0, 2, 0, 2, 2, 2, 1, 2, 2, 1, 2,
       0, 0, 1, 2, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 0])

In [16]:
trainlabels=pd.DataFrame(labels,y_train)
trainlabels

0
Class             
Iris-virginica   2
Iris-setosa      1
Iris-setosa      1
Iris-setosa      1
Iris-versicolor  2
...             ..
Iris-versicolor  2
Iris-virginica   2
Iris-setosa      1
Iris-versicolor  2
Iris-virginica   0

[90 rows x 1 columns]

In [17]:
Iris_virginica = trainlabels.loc['Iris-virginica']
Iris_setosa = trainlabels.loc['Iris-setosa']
Iris_versicolor = trainlabels.loc['Iris-versicolor']

In [18]:
Iris_virginica[Iris_virginica.columns[0]].value_counts()

0    23
2     9
Name: 0, dtype: int64

In [19]:
Iris_setosa[Iris_setosa.columns[0]].value_counts()

1    27
Name: 0, dtype: int64

In [20]:
Iris_versicolor[Iris_versicolor.columns[0]].value_counts()

2    28
0     3
Name: 0, dtype: int64

In [21]:
# predict cluster
testlabels = kmeansmodel.predict(X_test)
testlabels

array([2, 1, 0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 1, 1, 1, 2, 0, 2, 2, 0, 1, 2,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 2, 0, 1,
       1, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 2, 1, 1, 1, 2])

In [22]:
testdata=pd.DataFrame(testlabels,y_test)
testdata

0
Class             
Iris-versicolor  2
Iris-setosa      1
Iris-virginica   0
Iris-versicolor  2
Iris-versicolor  0
Iris-setosa      1
Iris-versicolor  2
Iris-virginica   0
Iris-versicolor  2
Iris-versicolor  2
Iris-virginica   0
Iris-setosa      1
Iris-setosa      1
Iris-setosa      1
Iris-setosa      1
Iris-versicolor  2
Iris-virginica   0
Iris-versicolor  2
Iris-versicolor  2
Iris-virginica   0
Iris-setosa      1
Iris-virginica   2
Iris-setosa      1
Iris-virginica   0
Iris-virginica   0
Iris-virginica   0
Iris-virginica   0
Iris-virginica   0
Iris-setosa      1
Iris-setosa      1
Iris-setosa      1
Iris-setosa      1
Iris-versicolor  2
Iris-setosa      1
Iris-setosa      1
Iris-virginica   0
Iris-versicolor  2
Iris-setosa      1
Iris-setosa      1
Iris-setosa      1
Iris-virginica   2
Iris-versicolor  2
Iris-versicolor  0
Iris-setosa      1
Iris-setosa      1
Iris-versicolor  2
Iris-virginica   0
Iris-virginica   0
Iris-versicolor  2
Iris-virginica   0
Iris-versicolor  2
Iris-virginica   0
Iris-versicolor  2
Iris-setosa      1
Iris-virginica   0
Iris-versicolor  2
Iris-setosa      1
Iris-setosa      1
Iris-setosa      1
Iris-versicolor  2

In [23]:
Iris_virginica_test = testdata.loc['Iris-virginica']
Iris_setosa_test = testdata.loc['Iris-setosa']
Iris_versicolor_test = testdata.loc['Iris-versicolor']

In [24]:
Iris_virginica_test[Iris_virginica_test.columns[0]].value_counts()

0    16
2     2
Name: 0, dtype: int64

In [25]:
Iris_setosa_test[Iris_setosa_test.columns[0]].value_counts()

1    23
Name: 0, dtype: int64

In [26]:
Iris_versicolor_test[Iris_versicolor_test.columns[0]].value_counts()

2    17
0     2
Name: 0, dtype: int64